# Generated by Django 4.0.4 on 2022-06-14 12:20

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta', models.BooleanField(default=False, null=True)),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, default='https://3000-sinchandevo-textanalyze-3x5fx1kmx2s.ws-us47.gitpod.io/static/images/user.svg', max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
