# Generated by Django 4.0.4 on 2022-06-16 10:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/opensourcegames/image/upload/v1655312306/TextAnalyser/user_xa7wjp.svg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='beta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
