# Generated by Django 4.0.4 on 2022-06-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_profile_avatar_alter_profile_beta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
