# Generated by Django 4.0.4 on 2022-06-16 11:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/opensourcegames/image/upload/v1655312306/TextAnalyser/user_xa7wjp.svg', max_length=255, null=True),
        ),
    ]
