# Generated by Django 4.0.4 on 2022-06-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
