# Generated by Django 4.0.4 on 2022-06-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
