# Generated by Django 4.0.4 on 2022-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gist',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=60),
        ),
    ]
