# Generated by Django 4.0.4 on 2022-07-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gist',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
