# Generated by Django 4.0.4 on 2022-07-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Unkown Author', max_length=60),
        ),
    ]
