# Generated by Django 4.0.4 on 2022-06-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyuser',
            name='auth_token',
        ),
        migrations.AddField(
            model_name='verifyuser',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
