# Generated by Django 4.0.4 on 2022-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDB',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=355)),
                ('slug', models.SlugField(max_length=234)),
            ],
        ),
    ]
