# Generated by Django 4.0.4 on 2022-06-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdb',
            name='slug',
            field=models.CharField(max_length=234),
        ),
    ]
